import api from '@/utils/api'

export default {
  getDegs(params) { return api.get('/analysis/degs', { params }) },
  getDegsChart(params) { return api.get('/analysis/degs/chart', { params }) },
  searchDegsGenes(params) { return api.get('/analysis/degs/gene-search', { params }) },
  getKegg(params) { return api.get('/analysis/kegg', { params }) },
  getRidge(params) { return api.get('/analysis/ridge', { params }) },
  getTrajectoryFiles(params) { return api.get('/analysis/trajectory/files', { params }) },
  getCellChat(params) { return api.get('/analysis/cellchat', { params }) },
  getCellChatChart() { return api.get('/analysis/cellchat/chart') },
  getCellChatNetwork(params) { return api.get('/analysis/cellchat/network', { params }) },
  getFilters() { return api.get('/analysis/metadata/filters') },
  // CBD3 新增
  getGeneDiffCelltype(params) { return api.get('/analysis/gene-diff/celltype', { params }) },
  getGeneDiffCelltypeChart(params) { return api.get('/analysis/gene-diff/celltype/chart', { params }) },
  getGeneDiffTvsN(params) { return api.get('/analysis/gene-diff/tvsn', { params }) },
  getGeneDiffTvsNChart(params) { return api.get('/analysis/gene-diff/tvsn/chart', { params }) },
  searchGeneDiffGenes(params) { return api.get('/analysis/gene-diff/gene-search', { params }) },
  getRocTn(params) { return api.get('/analysis/roc/tn', { params }) },
  getRocCelltype(params) { return api.get('/analysis/roc/celltype', { params }) },
  searchRocGenes(params) { return api.get('/analysis/roc/gene-search', { params }) },
  getRocChart(params) { return api.get('/analysis/roc/chart', { params }) },
  getPrs(params) { return api.get('/analysis/prs', { params }) },
  getPrsScatter(params) { return api.get('/analysis/prs/scatter', { params }) },
  searchPrsGenes(params) { return api.get('/analysis/prs/gene-search', { params }) },
  computePrsNetwork(data) { return api.post('/network/prs', data) },
  computePrsByGenes(data) { return api.post('/network/prs/genes', data) },
  getPrsSubnetwork(data) { return api.post('/network/prs/subnetwork', data) },
  getBiomkCellchat(params) { return api.get('/analysis/biomk-cellchat', { params }) },
  searchBiomkCellchatGenes(params) { return api.get('/analysis/biomk-cellchat/gene-search', { params }) },
  getBiomkCellchatNetwork(params) { return api.get('/analysis/biomk-cellchat/network', { params }) },
  getPseudotimeTrajectory(params) { return api.get('/analysis/pseudotime/trajectory', { params }) },
  getPseudotimeGeneExpr(params) { return api.get('/analysis/pseudotime/gene-expr', { params }) },
  searchPseudotimeGenes(params) { return api.get('/analysis/pseudotime/gene-search', { params }) },
  getPpiEdges(params) { return api.get('/analysis/ppi/edges', { params }) },
  getPpiTopology(params) { return api.get('/analysis/ppi/topology', { params }) },
  getGeneExprSummary(params) { return api.get('/analysis/gene-expr-summary', { params }) },
}
